
# Site settings
title: BSides Munich 2020
subtitle: "A free security conference in the heart of Bavaria"
url: "https://2020.bsidesmunich.org" # the base hostname & protocol for your site
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

collections:
  talks:
    output: true #Does not work
    permalink: /:collection/:title/
#    /:collection/:title/index.html
  workshops:
    output: true #Does not work
    permalink: /:collection/:title/
#    permalink: /:collection/:title

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

imprint:
  #name: "BSides Munich, Mr. Frederic Mohr"
  name: "Muc:Sec e.V."
  addressco: "c/o Johnson"
  address: "Curiestraße 3, 80999 München"
  email: "info [at] bsidesmunich [dot] org"
  #phone: "+49 89

conference:
  # contact e-mail, e.g., for sponsors
  email: organizers@bsidesmunich.org
  twitter: https://twitter.com/bsidesmunich
  newsletter: http://eepurl.com/dNWt2w
  sponsors:
    #show the sponsors in the footer of every page
    lookingfor: false
    footer: false #BETA
    # sponsor logos should all have the same format (at least width)
# uncomment it to fill sponsors in
    platinum:
      
    gold:
      
    silver:
      
    bronze:

    community:
    - name: Elbsides
      logo: /img/sponsors/elbsides.png
      uri: https://elbsides.de/

  links:
    sponsorpackage_en_uri: /files/BSidesMunich2020Sponsorship-English.pdf
    sponsorpackage_de_uri: /files/BSidesMunich2020Sponsorship-Deutsch.pdf
    cfw_uri: #
    cfp_uri: #
    contickets_uri: #
    contickets_state: "Looking for venue"
  dates: 
    deadline_tickets: tba
    deadline_cfp: tba
    workshops: "Spring 2020"
    conference: "Spring 2020"
  venue:
    workshopsday:
      address: "Looking for one"
      details: ""
      maps_uri: 
    conferenceday:
      address: "Looking for one"
      maps_uri: 
  archive:
    a2019:
      participants: 300
      presentations: 15
      workshops: 6
      hours: 35
      website_uri: https://2018.bsidesmunich.org
      recordings_uri: https://www.youtube.com/watch?v=zq2Ge3EQMpE&list=PL8N5HiRDvZ-etExLvF5766VOD0CkZTSZx
      slider:
      - src: img/slider2018/organizers.jpg
      - src: img/slider2018/MS-P4080195.jpg
      - src: img/slider2018/MS-P4090241.jpg
      - src: img/slider2018/MS-P4090485.jpg
      - src: img/slider2018/MS-P4090947.jpg

compress_html:
  clippings: all
  comments: all
  ignore:
    envs: []
  blanklines: false
  profile: false

exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "Makefile"
  - "INSTALL.txt"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

pre_build:
  commands:
    - export LC_ALL="C.UTF-8"
    - export LANG="en_US.UTF-8"
    - export LANGUAGE="en_US.UTF-8"
