
# Site settings
title: BSides Munich 2020
subtitle: "A free security conference in the heart of Bavaria"
url: "https://2020.bsidesmunich.org" # the base hostname & protocol for your site
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

collections:
  talks:
    output: true #Does not work
    permalink: /:collection/:title/
#    /:collection/:title/index.html
  workshops:
    output: true #Does not work
    permalink: /:collection/:title/
#    permalink: /:collection/:title

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

imprint:
  #name: "BSides Munich, Mr. Frederic Mohr"
  name: "MUC:SEC e.V."
  addressco: "c/o LastBreach"
  address: "Rohrauerstraße 70, 81477 München"
  email: "manager [at] bsidesmunich [dot] org"
  #phone: "+49 89
  chair: Christoph Kemetmüller
  vicechair: Ana Oprea


conference:
  # contact e-mail, e.g., for sponsors
  email: organizers@bsidesmunich.org
  twitter: https://twitter.com/bsidesmunich
  newsletter: http://eepurl.com/dNWt2w
  notice: 
    - "**BSides Munich 2020 will be held as a virtual event. Please take a look at the [agenda](/agenda) for details.**

In this highly dynamic situation we took the tough decision to cancel the BSides Munich 2020 conference and workshops. Our goal is to provide a forum for communication and cooperation. In the current situation this would contradict public health recommendations. We would like to thank the community, our sponsors and partners for their great support and understanding in these difficult times."

  sponsors:
    contact: sponsors (at) bsidesmunich (dot) org
    #show the sponsors in the footer of every page
    lookingfor: false
    footer: false #BETA
    # sponsor logos should all have the same format (at least width)
# uncomment it to fill sponsors in

    community:
    - name: Elbsides
      logo: /img/sponsors/elbsides.png
      uri: https://elbsides.de

    - name: BSides Stuttgart
      logo: /img/sponsors/BSidesStuttgart.png
      uri: https://www.bsidesstuttgart.org

  links:
    sponsorpackage_en_uri: /files/BSidesMunich2020Sponsorship-English.pdf
    sponsorpackage_de_uri: /files/BSidesMunich2020Sponsorship-Deutsch.pdf
    cfw_uri: https://forms.gle/oACeH7J5QQzhHTKYA
    cfp_uri: https://forms.gle/8njVYBPsshUXrAHq9
    contickets_uri: 
    contickets_state: 
      
  dates: 
    deadline_tickets: 
    deadline_cfp: 
    workshops: 
    conference: 2020-08-23

  venue:
    workshopsday:
      address: 
      details: ""
      gps: 
    conferenceday:
      address: 
      details: ""
      gps:
  archive:
    a2019:
      title: "BSides Munich 2019"
      participants: 343
      presentations: 13
      workshops: 8
      hours: 38
      website_uri: https://2019.bsidesmunich.org
      recordings_uri: https://www.youtube.com/watch?v=u8twBNM7LmQ&list=PL8N5HiRDvZ-f063NRSyVm4gEycdI54ZXD
      slider:
      - src: img/slider2019/IMG_20190325_112110.jpg
      - src: img/slider2019/IMG_20190329_170605.jpg
      - src: img/slider2019/P3240090.jpg
      - src: img/slider2019/P3240167.jpg
      - src: img/slider2019/P3250641.jpg
      - src: img/slider2019/P3250925.jpg
compress_html:
  clippings: all
  comments: all
  ignore:
    envs: []
  blanklines: false
  profile: false

exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "Makefile"
  - "INSTALL.txt"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

pre_build:
  commands:
    - export LC_ALL="C.UTF-8"
    - export LANG="en_US.UTF-8"
    - export LANGUAGE="en_US.UTF-8"
